config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  ActiveAdmin.routes(self)
  root "academics#index"
  get "academics/about"
  get "academics/index"
  get "academics", to: "academics#index"

  get "attendances/mark_all" => "attendances#mark_all"

  resources :users
  resources :academics
  resources :timetables
  resources :time_slots
  resources :subjects
  resources :student_subjects
  resources :faculty_subjects
  resources :attendances
end

app/controllers/academics_controller.rb
class AcademicsController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/academics_helper.rb
module AcademicsHelper
end

app/views/academics/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <!--<a class="navbar-brand" href="#">Academic App</a> -->
  <%= link_to 'Academic App', root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <!--<a<a class="nav-link" href="#">Link</a>-->
        <%= link_to 'About Us', academics_about_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Users', users_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Subjects', subjects_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Faculty-Subjects', faculty_subjects_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Student-Subjects', student_subjects_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Time Slots', time_slots_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Timetables', timetables_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Atendances', attendances_path, class:"nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Add User', new_user_path, class:"nav-link" %>
          <%#app/views/users/new.html.erb%>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/academics/about.html.erb
<h1>About Us ... at app/views/academics/about.html.erb</h1>
<p> <%=@about%>  </p>

app/views/academics/index.html.erb
<h1>Academics#index</h1>