config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  ActiveAdmin.routes(self)
  root "academics#index"
  get "academics/about"
  get "academics/index"
  get "academics", to: "academics#index"

  get "attendances/mark_all" => "attendances#mark_all"

  resources :users
  resources :academics
  resources :timetables
  resources :time_slots
  resources :subjects
  resources :student_subjects
  resources :faculty_subjects
  resources :attendances
end

app/controllers/timetables_controller.rb
class TimetablesController < ApplicationController
  before_action :set_timetable, only: %i[ show edit update destroy ]

  # GET /timetables or /timetables.json
  def index
    @timetables = Timetable.all
  end

  # GET /timetables/1 or /timetables/1.json
  def show
  end

  # GET /timetables/new
  def new
    @timetable = Timetable.new
  end

  # GET /timetables/1/edit
  def edit
  end

  # POST /timetables or /timetables.json
  def create
    @timetable = Timetable.new(timetable_params)

    respond_to do |format|
      if @timetable.save
        format.html { redirect_to @timetable, notice: "Timetable was successfully created." }
        format.json { render :show, status: :created, location: @timetable }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @timetable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timetables/1 or /timetables/1.json
  def update
    respond_to do |format|
      if @timetable.update(timetable_params)
        format.html { redirect_to @timetable, notice: "Timetable was successfully updated." }
        format.json { render :show, status: :ok, location: @timetable }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @timetable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timetables/1 or /timetables/1.json
  def destroy
    @timetable.destroy
    respond_to do |format|
      format.html { redirect_to timetables_url, notice: "Timetable was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timetable
      @timetable = Timetable.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def timetable_params
      params.require(:timetable).permit(:day, :slot, :subject_id)
    end
end

app/helpers/timetables_helper.rb
module TimetablesHelper
end

app/views/timetables/_form.html.erb
<%= form_with(model: timetable) do |form| %>
  <% if timetable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(timetable.errors.count, "error") %> prohibited this timetable from being saved:</h2>
      <ul>
        <% timetable.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :day %>
    <%= form.select :day, ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"] %>
    <%#= f.collection_select :provider_id, Provider.order(:name),:id,:name, include_blank: true %>
    <%#= f.select :desired_attribute, ['option1', 'option2']%>
  </div>
  <div class="field">
    <%= form.label :slot %>
    <%= form.number_field :slot %>
  </div>
  <div class="field">
    <%= form.label :subject_id %>
    <%= form.number_field :subject_id %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/timetables/edit.html.erb
<h1>Editing Timetable</h1>

<%= render 'form', timetable: @timetable %>

<%= link_to 'Show', @timetable %> |
<%= link_to 'Back', timetables_path %>

app/views/timetables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Timetables</h1>

<table>
  <thead>
    <tr>
      <th>Day</th>
      <th>Slot</th>
      <th>Subject</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @timetables.each do |timetable| %>
      <tr>
        <td><%= timetable.day %></td>
        <td><%= timetable.slot %></td>
        <td><%= timetable.subject_id %></td>
        <td><%= link_to 'Show', timetable %></td>
        <td><%= link_to 'Edit', edit_timetable_path(timetable) %></td>
        <td><%= link_to 'Destroy', timetable, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Timetable', new_timetable_path %>

app/views/timetables/new.html.erb
<h1>New Timetable</h1>

<%= render 'form', timetable: @timetable %>

<%= link_to 'Back', timetables_path %>

app/views/timetables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Day:</strong>
  <%= @timetable.day %>
</p>

<p>
  <strong>Slot:</strong>
  <%= @timetable.slot %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @timetable.subject_id %>
</p>

<%= link_to 'Edit', edit_timetable_path(@timetable) %> |
<%= link_to 'Back', timetables_path %>