config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  ActiveAdmin.routes(self)
  root "academics#index"
  get "academics/about"
  get "academics/index"
  get "academics", to: "academics#index"

  get "attendances/mark_all" => "attendances#mark_all"

  resources :users
  resources :academics
  resources :timetables
  resources :time_slots
  resources :subjects
  resources :student_subjects
  resources :faculty_subjects
  resources :attendances
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user, foreign_key: :faculty_id, inverse_of: :attendances, :optional => true
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_attendance, only: %i[ show edit update destroy ]

  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  #26/11^

  # GET /attendances or /attendances.json
  def index
    @attendances = Attendance.all
  end

  # GET /attendances/1 or /attendances/1.json
  def show
  end

  # GET /attendances/new
  def new
    # @attendance = Attendance.new
    #26/11^v
    @attendance = current_user.attendances.build
  end

  # Mark from students list 27/11

  def mark_all
    #render html: "Testing from app/controllers/attendances_controller.rb#mark"
    # Look in views/attendances/mark.html.erb for the view part
    @students = User.student
    if params[:pre] == true
      puts "present--------------------------------------------------------------------"
    else
      puts "absent--------------------------------------------------------------------"
    end
    puts params[:these_ids[1]]
  end

  # GET /attendances/1/edit
  def edit
  end

  # POST /attendances or /attendances.json
  def create
    #@attendance = Attendance.new(attendance_params)
    @attendance = current_user.attendances.build(attendance_params)

    respond_to do |format|
      if @attendance.save
        format.html { redirect_to @attendance, notice: "Attendance was successfully created." }
        format.json { render :show, status: :created, location: @attendance }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendances/1 or /attendances/1.json
  def update
    respond_to do |format|
      if @attendance.update(attendance_params)
        format.html { redirect_to @attendance, notice: "Attendance was successfully updated." }
        format.json { render :show, status: :ok, location: @attendance }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1 or /attendances/1.json
  def destroy
    @attendance.destroy
    respond_to do |format|
      format.html { redirect_to attendances_url, notice: "Attendance was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user #26/11
    @attendance = current_user.attendances.find_by(id: params[:id])
    redirect_to attendances_path, notice: "Not authorised to edit this attendance" if @attendance.nil?
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_attendance
    @attendance = Attendance.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def attendance_params
    params.require(:attendance).permit(:date, :slot, :faculty_id, :subject_id, :student_id)
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/attendances/_form.html.erb
<%= form_with(model: attendance) do |form| %>
  <% if attendance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>
      <ul>
        <% attendance.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>
  <div class="field">
    <%= form.label :slot %>
    <%= form.number_field :slot %>
  </div>
  <div class="field">
    <%= form.label :faculty_id %>
    <%#= form.number_field :faculty_id, id: :attendance_user_id, value: current_user.id, :readonly => true %>
    <%= form.number_field :faculty_id, value: current_user.id, :readonly => true %>
    <%#= form.number_field :faculty_id %>
  </div>
  <div class="field">
    <%= form.label :subject_id %>
    <%= form.number_field :subject_id %>
  </div>
  <div class="field">
    <%= form.label :student_id %>
    <%= form.number_field :student_id %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/attendances/_form_mark_all.html.erb
<% if student %>
  <%= student.name %>
<% end %>

app/views/attendances/edit.html.erb
<h1>Editing Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Show', @attendance %> |
<%= link_to 'Back', attendances_path %>

app/views/attendances/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Attendances</h1>
<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Slot</th>
      <th>Faculty</th>
      <th>Subject</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @attendances.each do |attendance| %>
      <tr>
        <td><%= attendance.date %></td>
        <td><%= attendance.slot %></td>
        <td><%= attendance.faculty_id %></td>
        <td><%= attendance.subject_id %></td>
        <td><%= attendance.student_id %></td>
        <td><%= link_to 'Show', attendance %></td>
        <%# if attendance.faculty_id == current_user.id #just hiding only %>
        <td><%= link_to 'Edit', edit_attendance_path(attendance) %></td>
        <td><%= link_to 'Destroy', attendance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%# end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Attendance', new_attendance_path %>
<br>
<%= link_to 'Mark Full Class Attendance', attendances_mark_all_path %>

app/views/attendances/mark_all.html.erb
<p id="notice"><%= notice %></p>
<h1>Mark all Attendances</h1>
<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Email</th>
      <th>Role</th>
      <!--<th colspan="3"></th>-->
      <!--<th colspan="2"></th>-->
      <th>Present</th>
    </tr>
  </thead>
  <tbody>


    <% @students.each do |student| %>
      <tr>
        <td><%= student.id %></td>
        <td><%= student.name %></td>
        <td><%= student.email %></td>
        <td><%= student.role %></td>
        <% att = Attendance.new(date: Date.today(), slot: 2, faculty_id: current_user.id, subject_id: 2, student_id: student.id) %>
        <%#att.save%>
        <td><%= check_box_tag 'present' %></td>


      </tr>
    <% end %>
  </tbody>
</table>
<br>
<br>
<%#= link_to 'New Attendance', new_attendance_path %>
<br>
<%#= link_to 'Mark Full Class Attendance', attendances_mark_path %>

app/views/attendances/new.html.erb
<h1>New Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Back', attendances_path %>

app/views/attendances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @attendance.date %>
</p>

<p>
  <strong>Slot:</strong>
  <%= @attendance.slot %>
</p>

<p>
  <strong>Faculty:</strong>
  <%= @attendance.faculty_id %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @attendance.subject_id %>
</p>

<p>
  <strong>Student:</strong>
  <%= @attendance.student_id %>
</p>

<%= link_to 'Edit', edit_attendance_path(@attendance) %> |
<%= link_to 'Back', attendances_path %>